name: lp_runningflutter
description: "lp_runningflutter."
publish_to: 'lp_runningflutter' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3  
  intl: ^0.17.0  
  mask_text_input_formatter: ^2.9.0 
  image_picker: ^0.8.4+4
  flutter_multi_formatter: ^2.1.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/stopwatch.png
    - lib/assets/images/athletes.png
    - lib/assets/images/coaches.png
    - lib/assets/images/training_types.png
    - lib/assets/images/logo.png
    - lib/assets/images/logo02.png
